export const en = {
  email_title_user_invoice: 'User Invoice',
  email_title_trip_cancel: 'Trip Cancelled',
  email_title_provider_invoice: 'Driver Invoice',
  email_title_main: 'Thanks for choosing',
  email_title_location: 'Location',
  email_title_from: 'from',
  email_title_to: 'to',
  email_title_trip_statistics: 'Your Trip Statistics',
  email_title_min: 'min',
  email_title_km: 'km',
  email_title_fare_breakdown: 'Fare Breakdown',
  email_title_base_price: 'Base price',
  email_title_per_km: 'Per Km',
  email_title_per_min: 'Per min',
  email_title_distance_cost: 'Distance Cost',
  email_title_time_cost: 'Time Cost',
  email_title_wait_time_cost: 'Wait Time Cost',
  email_title_tax_fee: 'Tax Fee',
  email_title_surge_fee: 'Surge Fee',
  title_referred_user_count: 'Total Usage',
  title_bussiness_in_country: 'Business In Country',
  title_is_toll: 'Toll',
  title_is_trip: 'Tip',
  max_split_user: 'Max Split Payment User',
  is_split_payment: 'Split Payment',
  is_split_payment_desc: 'Split trip Payment With Friend',
  title_total_payment: 'Total',
  button_referral_history: 'Referral history',
  button_delete_city_boundary: 'Remove Boundary',
  title_select_payment_gateway: 'Select Payment Gateway',
  title_send_request: 'Send Request',
  title_corporate_wallet_limit: 'Amount Limit',
  button_add_limit: 'Amount Limit',
  email_title_referral_bonus: 'Referral Bonus',
  email_title_promo_bonus: 'Promo Bonus',
  email_title_payment: 'Payment',
  email_title_credit_card: 'Credit Card',
  email_title_provider_detail: 'Driver Details',
  title_vehicle_detail: 'Vehicle Detail',
  email_title_name: 'Name',
  email_title_phone: 'Phone',
  email_title_email: 'Email',
  email_title_support: 'Support',
  email_title_contact_us: 'Contact us',
  email_title_track: 'Track it down.',
  email_title_other_info:
    'with questions about your trip. Leave something behind?',
  sub_menu_title_corporate: 'Corporate',
  sub_menu_title_running_requests: 'Running Requests',
  menu_title_terms_and_privacy_setting: 'Terms And Privacy Setting',
  title_total_cancelled_by_schedule: 'Schedule Trip Cancelled',
  title_total_cancelled: 'Cancelled',
  message_welcome_login: 'Welcome, Please Login',
  title_add_dispatcher: 'Add Dispatcher',
  title_cancle_by_user: 'Cancle By User',
  title_cancle_by_provider: 'Cancle By Driver',
  button_add_new_document: 'Add New Document',
  title_add_provider: 'Add Driver',
  title_total_running_trip: 'Running',
  title_wallet: 'Wallet',
  title_wallet_payment: 'Wallet Payment',
  title_app_version: 'App Version',
  title_total_cities: 'Total City',
  title_total_wallet_payment: 'Wallet',
  title_total_remaining_payment: 'Remaining',
  title_is_business: 'Business',
  title_is_ride_share: 'Ride Share',
  title_price_type: 'Pricing Type',
  title_ride_share_limit: 'Ride Share Max Limit',
  title_log_in: 'Log In',
  button_forgot_password: 'FOrgot Your Password',
  title_welcome: 'Welcome',
  title_select_date_time: 'Select Date & Time',
  title_image: 'Image',
  unit_km: 'km',
  unit_mile: 'mile',
  unit_min: 'min',
  unit_by_km: '/km',
  unit_by_mile: '/mile',
  unit_by_min: '/min',
  title_on: 'ON',
  title_off: 'OFF',
  title_add_new: 'Add New',
  title_profile: 'Profile',
  title_first_name: 'First Name',
  title_last_name: 'Last Name',
  title_mentor: 'Mentor',
  title_name: 'Name',
  title_brand_name: 'Brand Name',
  title_unique_code: 'Unique Code',
  title_expired_date: 'Expired Date',
  title_please_select_date: 'Please Select Date',
  titel_company_name: 'Company Name',
  title_email: 'Email',
  title_phone: 'Phone',
  title_address: 'Address',
  title_zipcode: 'Zipcode',
  title_status: 'Status',
  title_trip_from: 'Trip From',
  title_amount: 'Amount',
  title_transfer_by: 'Transfer By',
  title_default: 'Default',
  title_date: 'Date',
  title_start_date: 'Start Date',
  title_end_date: 'End Date',
  title_time: 'Time',
  title_edit_profile: 'Edit Profile',
  title_edit_detail: 'Edit Detail',
  title_taxi_model: 'Taxi Model',
  title_registration_number: 'Registration Number',
  title_sub_admin: 'Sub Admin',
  title_admin: 'Admin',
  question_already_register: 'Already haven an account ? Login',
  question_forgot_password: 'Forgot your password?',
  question_not_register: "Haven't account yet ? Register",
  message_welcome: 'Welcome, Please Register',
  button_profile: 'Profile',
  button_register: 'Register',
  button_login: 'Login',
  button_logout: 'Logout',
  button_action: 'Action',
  button_edit: 'Edit',
  button_update: 'Update',
  button_submit: 'Submit',
  button_add: 'Add',
  button_save: 'Save',
  button_detail: 'Detail',
  button_invoice: 'Invoice',
  button_history: 'History',
  button_pre: 'Pre',
  button_next: 'Next',
  button_export_excel: 'Export',
  button_apply: 'Apply',
  button_remove: 'Remove',
  button_delete: 'Delete',
  button_delete_account: 'Delete Account',
  button_close: 'Close',
  'button_select=': 'Select',
  button_password: 'Password',
  button_current_password: 'Current Password',
  button_banking_detail: 'Banking Detail',
  button_approve: 'Approve',
  button_decline: 'Decline',
  button_cancle_trip: 'Cancle Trip',
  button_calculate_estimate: 'Calculate Estimate',
  button_ride_now: 'Ride Now',
  button_assign_now: 'Assign now',
  button_add_new_dispatcher: 'Add New Dispatcher',
  button_other_payment: 'UPI/Other',
  button_cash_payment: 'Cash',
  button_add_new_hotel: 'Add New Hotel',
  button_cancel: 'Cancel',
  sort_asc: 'Ascending',
  sort_desc: 'Descending',
  menu_title_send_mass_notification: 'Send Mass Notification',
  menu_title_future_requests: 'Future Request',
  button_view: 'View',
  button_view_download: 'Download',
  button_view_detail: 'View Detail',
  button_view_history: 'View History',
  button_view_map: 'View Map',
  button_view_invoice: 'View Invoice',
  button_view_documents: 'View Document',
  button_view_no_document: 'No Document',
  button_view_photo: 'View Photo',
  button_used_promo_codes: 'Used Promo Codes',
  button_view_statements: 'View Statements',
  button_user_detail: 'User Detail',
  button_provider_detail: 'Driver Detail',
  title_user_details: 'User Details',
  title_provider_details: 'Driver Details',
  title_create_trip: 'Create Trip',
  title_user_rate: 'User Rate',
  title_provider_rate: 'Driver Rate',
  title_comment: 'Comment',
  title_trip: 'Trip',
  title_trips: 'Trips',
  title_user: 'User',
  title_hotel: 'Hotel',
  title_users: 'Users',
  title_user_name: 'User Name',
  title_user_email: 'User Email',
  title_provider: 'Driver',
  title_providers: 'Drivers',
  title_provider_name: 'Driver Name',
  title_provider_email: 'Driver Email',
  title_provider_phone: 'Driver Phone',
  title_partner: 'Partner',
  title_partners: 'Partners',
  title_partner_name: 'Partner Name',
  title_partner_email: 'Partner Email',
  title_dispatcher: 'Dispatcher',
  title_dispatchers: 'Dispatchers',
  title_dispatcher_name: 'Dispatcher Name',
  title_dispatcher_email: 'Dispatcher Email',
  title_dispatcher_login: 'Dispatcher Login',
  title_hotel_login: 'Hotel Login',
  title_car: 'Car',
  title_car_id: 'Car Id',
  title_plate_no: 'Vehicle No',
  title_id: 'ID',
  title_trip_id: 'Trip ID',
  title_user_id: 'User ID',
  title_provider_id: 'Driver ID',
  title_partner_id: 'Partner ID',
  title_partner_profit: 'Partner Profit',
  title_pay_to_partner: 'Pay to partner',
  title_sort: 'SORT',
  title_search: 'SEARCH',
  title_date_filter: 'DATE FILTER',
  title_cancellation_reason: 'Cancellation Reason',
  title_cancel_by: 'Cancel By',
  title_cancel_by_user: 'Cancelled by User',
  title_cancel_by_Driver: 'Cancelled by Driver',
  title_description: 'Description',
  title_service_type: 'Service Type',
  title_accessibility: 'Accessibility',
  title_gender: 'Gender',
  title_bussiness: 'Business',
  title_promo: 'Promo code',
  title_promo_type: 'Type',
  title_all_cities: 'All Cities',
  title_bank_code: 'Bank Code',
  title_bank_id: 'Bank Id',
  title_account_id: 'Account ID',
  title_value: 'Value',
  title_uses: 'Uses',
  title_user_promo_used: 'User Used',
  title_state: 'State',
  title_is_expired: 'Is Expired',
  title_forgot_password: 'Forgot Password',
  title_new_password: 'New Password',
  title_partner_login: 'Partner Login',
  menu_title_admin: 'Admin Settings',
  menu_title_requests: 'Requests',
  menu_title_payments: 'Payment',
  menu_title_trip_payments: 'Trip Payment',
  menu_title_settings: 'Settings',
  menu_title_basic_settings: 'Basic Settings',
  menu_title_languages: 'Trip Languages List',
  menu_title_mail_sms_template: 'Mail & SMS Template',
  menu_title_schedules: 'Schedules',
  menu_title_city_type: 'Service Types',
  menu_title_city_service_types: 'Type And City Association',
  menu_title_create_requests: 'Create Request',
  menu_title_bank_detail: 'Bank Detail',
  menu_title_profile: 'Profiles',
  menu_title_partner_earning: 'Partner Earning',
  menu_title_manage_vehicle: 'Manage Vehicle',
  menu_title_report: 'Report',
  sub_menu_title_referral_report: 'User Referral Report',
  sub_menu_title_provider_referral_report: 'Driver Referral Report',
  sub_menu_title_partners: 'Partners',
  sub_menu_title_partner_payments: 'Partner Payments',
  sub_menu_title_partner_weekly_payments: 'Partner Weekly Payments',
  sub_menu_title_dispatcher: 'Dispatchers',
  sub_menu_title_hotel: 'Hotels',
  menu_title_dashboard: 'Dashboard',
  sub_menu_title_requests_on_today: "Today's Requests",
  sub_menu_title_completed_requests: 'Completed Requests',
  sub_menu_title_schedule_requests: 'Scheduled Requests',
  title_trip_status_completed: 'Completed',
  sub_menu_title_reviews: 'Reviews',
  sub_menu_title_cancellation_reason: 'Cancellation Reason',
  menu_title_map_view: 'Map View',
  sub_menu_title_providers_map_view: 'Drivers Map View',
  sub_menu_title_payments: 'Payments',
  title_provider_track: 'Driver Tracking',
  menu_title_providers: 'Drivers',
  sub_menu_title_online_providers: 'Online Drivers',
  sub_menu_title_approved_providers: 'Approved Drivers',
  sub_menu_title_pending_for_approve_providers: 'Unapproved Drivers',
  sub_menu_title_block_users: 'Blocked Users',
  sub_menu_title_trip_earnings: 'Trip Earnings',
  sub_menu_title_daily_earning: 'Daily Earning',
  sub_menu_title_weekly_earning: 'Weekly Earning',
  sub_menu_title_provider_earnings: 'Driver Earnings',
  sub_menu_title_provider_daily_earning: 'Driver Daily Earning',
  sub_menu_title_provider_weekly_earning: 'Driver Weekly Earning',
  sub_menu_title_pending_payments: 'Pending Payments',
  sub_menu_title_wallet_history: 'Wallet History',
  sub_menu_title_transaction_history: 'Transaction History',
  sub_menu_title_installation_settings: 'Installation Settings',
  sub_menu_title_documents_for_country: 'Documents',
  sub_menu_title_promotions: 'Promo Codes',
  sub_menu_title_sms_template: 'SMS Template',
  sub_menu_title_mail_template: 'Mail Template',
  menu_title_users: 'Users',
  title_provider_earning: 'Driver Earning',
  title_email_unique_title: 'Email Unique Title',
  title_email_title: 'Email Title',
  title_email_content: 'Email Content',
  title_email_admin_info: 'Email Admin Info',
  title_select_email_unique_title: 'Select Email Unique Title',
  title_sms_unique_title: 'SMS Unique Title',
  title_select_sms_unique_title: 'SMS Content',
  title_sms_content: 'Select SMS Unique Title',
  dlt_template_id: 'DLT Template ID',
  title_payment_gateway: 'Payment Gateway',
  title_total_request: 'Request',
  title_completed: 'Completed',
  title_total: 'Total',
  title_payment: 'Payment',
  title_referral: 'Referral',
  title_payment_mode: 'Payment Mode',
  title_payment_status: 'Payment Status',
  title_card: 'UPI/Others',
  title_cash: 'Cash',
  title_apple_pay: 'Apple Pay',
  title_both: 'Both',
  title_card_payment: 'Card Payment',
  title_cash_payment: 'Cash Payment',
  title_other_pricing: 'Other Pricing',
  title_driver_wallet_setting: 'Driver Wallet Setting',
  title_user_payment_setting: 'User Payment Setting',
  title_phone_number_length: 'Phone Number Length',
  title_payment_to_driver: 'Payment to Driver',
  title_pay_by_card: 'Pay By UPI/Others',
  title_pay_by_cash: 'Pay By Cash',
  title_yet_to_be_paid: 'Yet to be paid',
  title_available: 'Available',
  title_waiting_for_trip: 'Waiting for Trip',
  title_active: 'Active',
  title_inactive: 'Inactive',
  title_offline: 'Offline',
  title_online: 'Online',
  title_trip_status: 'Trip Status',
  title_trip_status_no_response: 'No response',
  title_trip_status_provider_start: 'Driver Start',
  title_trip_status_coming: 'Coming',
  title_trip_status_arrived: 'Arrived',
  title_trip_status_waiting: 'Waiting',
  title_trip_status_trip_started: 'Started',
  title_trip_status_in_trip: 'In Trip',
  titel_trip_rejected: 'Rejected',
  title_select_service_type: 'Select Service Type',
  title_select_city: 'Select City...',
  title_response: 'Response',
  titel_request_not_completed: 'Request Not Completed',
  title_earning: 'Earning',
  title_promo_referral_amount: 'Promo',
  title_provider_fees: 'Driver Fees',
  title_current_rate: 'Current Rate',
  title_trip_end_date: 'Trip End Date',
  title_invoice_total_distance: 'Distance',
  title_invoice_total_time: 'Time',
  title_invoice_total_wait_time: 'Wait Time',
  title_date_time: 'Date Time',
  title_min_fair: 'Min. Fare',
  title_invoice_distance_fees: 'Distance Fees',
  title_invoice_time_fees: 'Time Fees',
  title_invoice_wait_time_fees: 'Wait Time Fees',
  title_invoice_tax_fees: 'Tax Fees',
  title_invoice_surge_fees: 'Surge Fees',
  title_invoice_service_fees: 'Service Fees',
  title_invoice_tax_price: 'Tax Price',
  title_registration_chart: 'Registration Chart',
  title_Payment_chart: 'Payment Chart',
  title_earning_chart: 'Earning Chart',
  title_request_chart: 'Request Chart',
  title_country_chart: 'Country Chart',
  title_version_chart: 'Version Chart',
  title_invoice_service_total: 'Service Total',
  title_pickup_address: 'Pickup Address',
  title_destination_address: 'Destination Address',
  title_trip_status_created: 'Created',
  title_trip_status_pending: 'Pending',
  title_request_time: 'User Created',
  title_reached_time: 'Driver Reached',
  title_start_time: 'Trip Started',
  title_end_time: 'Trip End at',
  title_created_at: 'Created At',
  title_trip_description: 'Trip Description',
  title_total_distance: 'Total Distance',
  title_total_time: 'Total Time',
  title_total_wait_time: 'Total Time',
  title_base_price: 'Base Price',
  title_distance_price: 'Distance Price',
  title_total_time_price: 'Time Price',
  title_wait_time_price: 'Wait Time Price',
  title_stop_wait_time_price: 'Stops Wait Time Price',
  title_stop_wait_time: 'Stops Wait Time',
  title_total_fixed_price: 'Fixed Price',
  title_sub_total: 'Sub Total',
  title_trip_total: 'Trip Total',
  title_promo_discount: 'Promo',
  title_refferal_discount: 'Referral',
  titel_view_in_detail: 'View In Detail',
  titel_view_provider: 'View Driver',
  title_completed_rate: 'Completed Rate',
  title_accepted_rate: 'Accepted Rate',
  title_statement_number: 'Statement Number',
  title_provider_have_cash: 'Driver Have Cash',
  title_pay_to_provider: 'Pay To Driver',
  title_previous_week_difference: 'Previous Week Difference',
  title_admin_paid: 'Admin Paid',
  title_remaining: 'Remaining',
  title_statement_date: 'Statement Date',
  title_payment_statement: 'Payment Statement',
  title_total_earnings: 'Total Earnings',
  title_cash_collected: 'Cash Collected',
  title_bank_deposite: 'Bank Deposite',
  title_pay: 'Pay',
  title_schedule: 'Schedule',
  title_schedule_timezone: 'TimeZone',
  title_today: 'Today',
  title_within_day: 'Within Day',
  title_code: 'Code',
  title_currency: 'Currency',
  title_sign: 'Sign',
  title_countries: 'Countries',
  title_country: 'Country',
  title_country_code: 'Country Code',
  title_city: 'City',
  title_cities: 'Cities',
  title_referral_bonus_to_user: 'Bonus to User',
  title_bonus_to_user_referral: 'Bonus to Referral',
  title_distance_for_base_price: 'Distance for Base Price',
  title_time_for_base_price: 'Time For Base Price (min)',
  title_price_per_unit_distance: 'Price Per Unit Distance',
  title_price_for_waiting_per_unit_time: 'Price for Waiting Per Unit Time',
  title_price_for_total_unit_time: 'Price Per Unit Time (min)',
  title_tax: 'Tax',
  title_max_space: 'Max Space',
  title_document: 'Document',
  title_option: 'Option',
  title_document_type: 'Document Type',
  title_optional: 'Optional',
  title_mandatory: 'Mandatory',
  title_customize: 'Customize',
  title_weekly_statement: 'Weekly statement',
  title_statements: 'Statements',
  title_bank_name: 'Bank Name',
  title_bank_branch: 'Bank Branch',
  title_bank_account_number: 'Bank Account Number',
  title_bank_account_holder_name: 'Bank Account Holder Name',
  title_bank_beneficiary_address: 'Bank Beneficiary Address',
  title_bank_unique_code: 'Bank Unique Code',
  title_bank_swift_code: 'Bank Swift Code',
  title_routing_number: 'Routing Number',
  title_SSN: 'SSN',
  title_birth_date: 'Birth Date',
  title_upload_id: 'Upload Your ID Proof',
  title_password: 'Password',
  title_type_name: 'Type Name',
  title_type_priority: 'Type Priority',
  title_type_image: 'Type Image',
  title_map_pin_image: 'Map Pin Image',
  title_ios_certificates: 'iOS Certificates',
  title_ios_user_cert_file: 'iOS User app push Certificate',
  title_ios_user_key_file: 'iOS User app push Key file',
  title_ios_user_passphrase: 'iOS User app push passphrase',
  title_ios_provider_cert_file: 'iOS Driver app push Certificate',
  title_ios_provider_key_file: 'iOS Driver app push Key file',
  title_ios_provider_passphrase: 'iOS Driver app push passphrase',
  title_theme_setting: 'Theme Settings',
  title_logo_image_name: 'Logo',
  title_title_image_name: 'Title Icon',
  title_mail_title_image_name: 'Mail Title Image',
  title_authorised_image_name: 'Authorised  Signature',
  title_id_proof: 'Id Proof',
  title_wallet_amount: 'Wallet Amount',
  title_add_cut: 'Add/Cut',
  title_wallet_description: 'From Where?',
  title_hotline_app: 'Hotline Customer Support App Keys',
  title_hotline_app_id: 'Hotline Customer Support App Id',
  title_hotline_app_key: 'Hotline Customer Support App key',
  title_search_text: 'Search...',
  title_all: 'All',
  title_number_of_cards: 'Number of Cards',
  title_payment_error: 'Payment Error',
  title_payment_message: 'Payment Message',
  title_charged: 'Charged',
  title_payment_request: 'Payment request',
  title_fees: 'Fees',
  title_total_trip: 'Total Trip',
  title_completed_trip: 'Completed Trip',
  title_total_online: 'Total Online',
  title_amount_for_pay: 'Amount for pay',
  title_paid: 'Paid',
  title_not_paid: 'N/A',
  title_pending: 'Pending',
  title_add_admin: 'Add Admin',
  title_edit_admin: 'Edit Admin',
  title_add_language: 'Add Language',
  title_timezone: 'Time Zone',
  title_bussiness_in_city: 'Business In City',
  title_distance_unit: 'Distance Unit',
  title_city_radius: 'City Radius (Km)',
  title_city_latitude: 'City Latitude',
  title_city_longitude: 'City Longitude',
  title_promo_apply_for_card: 'Promo Apply for Card',
  title_promo_apply_for_cash: 'Promo Apply for Cash',
  title_city_code: 'City Code',
  title_zip_code: 'Zip Code',
  title_latitude: 'Default Map Load Latitude',
  title_longitude: 'Default Map Load Longitude',
  title_is_ask_user_for_fixed_fare: 'Ask User For Fixed Fare',
  title_provider_min_wallet_amount_set_for_received_cash_request:
    'Driver Min. Wallet Amount For Cash',
  title_is_check_provider_wallet_amount_for_received_cash_request:
    'Check Wallet Amount For Cash',
  title_is_provider_earning_set_in_wallet_on_cash_payment:
    'Driver Amount Add In Wallet By Cash Payment',
  title_is_provider_earning_set_in_wallet_on_other_payment:
    'Driver Amount Add In Wallet By Other Payment',
  title_type: 'Type',
  title_add_city_type: 'Add City Type',
  title_price_for_waiting_time: 'Price For Waiting Time (min)',
  title_is_surge_hours: 'Is Surge Hours',
  title_surge_time_start: 'Surge Time Start',
  title_surge_time_end: 'Surge Time End',
  title_surge_multiplier: 'Surge Multiplier',
  title_provider_profit: 'Driver Profit',
  title_waiting_time_start_after_minute: 'Waiting Time Start After Minute',
  title_cancellation_fee: 'Cancellation Fee',
  title_add_type: 'Add Type',
  title_review_detail: 'Review Detail',
  title_add_new_country: 'Add New Country',
  title_country_bussiness: 'Business In Country',
  title_user_referral_max_use: 'Referral Max Usage (User)',
  title_phone_number_min_length: 'Phone Number Min Length',
  title_phone_number_max_length: 'Phone Number Max Length',
  title_countyry_name: 'Country Name',
  title_currency_code: 'Currency Code',
  title_currency_sign: 'Currency Sign',
  title_country_time_zone: 'Time Zone',
  title_country_phone_code: 'Phone Code',
  title_referral_in_country: 'User Referral',
  title_default_referral_bonus_to_user:
    'Referral Bonus Amount to Friend (User)',
  title_default_bonus_to_referral_user: 'Referral Bonus Amount to Self (User)',
  title_partner_weekly_statement: 'Partner Weekly Statements',
  title_authorized_signature: 'Authorised Signature',
  button_export_pdf: 'Download PDF',
  title_partner_fees: 'Partner Fees',
  title_provider_daily_earning: 'Driver Daily Earning',
  title_provider_daily_statement: 'Driver Daily Statement',
  title_surge: 'Surge',
  title_basic_settings: 'Basic Settings',
  title_define_city_area: 'Define City Area',
  title_settings: 'Settings',
  title_basic_app_settings: 'Basic App Settings',
  title_select_country: 'Select Country',
  title_admin_country: 'Admin Country',
  title_admin_currency_code: 'Admin Currency Code',
  title_admin_currency: 'Admin Currency',
  title_admin_timezone: 'Admin TimeZone',
  title_admin_phone_number: 'Admin Phone Number',
  title_admin_email_address: 'Admin Email Address',
  title_contact_email: 'Contact Email',
  title_provider_timeout_in_seconds: 'Driver Timeout in seconds',
  title_default_search_radius: 'Default Search Radius',
  title_scheduled_request_pre_start_minutes:
    'Scheduled Request Pre Start Minutes',
  title_number_of_loop_for_scheduled_requests:
    'Number of loop for find nearest driver',
  title_notification_settings: 'Notification Settings',
  title_sms_notification: 'SMS Notification',
  title_email_notification: 'E-mail Notification',
  title_user_path: 'Draw road path in User app',
  title_provider_path: 'Draw road path in Driver app',
  title_get_referral_profit_on_card_payment:
    'Get referral profit on card payment',
  title_get_referral_profit_on_cash_payment:
    'Get referral profit on cash payment',
  title_user_email_verification: 'User Email Verification',
  title_provider_email_verification: 'Driver Email Verification',
  title_user_sms: 'User Mobile Number Verification',
  title_provider_sms: 'Driver Mobile Number Verification',
  title_android_user_app_version_code: 'Android User App Version',
  title_android_provider_app_version_code: 'Android Driver App Version',
  title_ios_user_app_version_code: 'IOS User App Version',
  title_ios_provider_app_version_code: 'IOS Driver App Version',
  title_android_user_app_force_update: 'Android User App Force Update',
  title_android_provider_app_force_update: 'Android Driver App Force Update',
  title_ios_user_app_force_update: 'IOS User App Force Update',
  title_ios_provider_app_force_update: 'IOS Driver App Force Update',
  title_installtion_settings: 'Installation Settings',
  title_sms_configuration: 'SMS Configuration',
  title_default_sms_gateway: 'Default SMS Gateway',
  title_msg91_authkey: 'MSG91 Authkey',
  title_msg91_sender: 'MSG91 Sender',
  title_twilio_account_sid: 'Twilio Account SID',
  title_twilio_auth_token: 'Twilio Auth Token',
  title_twilio_number: 'Twilio Number',
  title_twilio_url: 'Twilio Call Url',
  title_payment_configuration: 'Payment Configuration',
  title_default_payment_gateway: 'Default Payment Gateway',
  title_stripe_secret_key: 'Stripe Secret Key',
  title_stripe_publishable_key: 'Stripe Publishable Key',

  title_razor_secret_key: 'Razor Secret Key',
  title_razor_key_id: 'Razor Key Id',
  title_email_configuration: 'Email Configuration',
  title_display_name: 'Display Name',
  title_domain_email_address: 'Domain Email Address',
  title_gcm_api_key: 'GCM API KEY',
  title_android_user_app_gcm_key: 'Android User App GCM Key',
  title_android_provider_app_gcm_key: 'Android Driver App GCM Key',
  title_google_places_api_key: 'Google Places API Key',
  title_android_user_app_google_key: 'Android User App Google Key',
  title_android_provider_app_google_key: 'Android Driver App Google Key',
  title_ios_user_app_google_key: 'iOS User App Google Key',
  title_ios_provider_app_google_key: 'iOS Driver App Google Key',
  title_web_app_google_key: 'Web App Google Key',
  title_android_app_url: 'Android App URL',
  title_android_client_app_url: 'Android Client App URL',
  title_android_driver_app_url: 'Android Driver App URL',
  title_ios_app_url: 'IOS App URL',
  title_ios_client_app_url: 'IOS Client App URL',
  title_ios_driver_app_url: 'IOS Driver App URL',
  title_app_name: 'Panel Name',
  title_admin_panel_name: 'Admin Panel Name',
  title_partner_panel_name: 'Partner Panel Name',
  title_dispatcher_panel_name: 'Dispatcher Panel Name',
  title_hotel_panel_name: 'Hotel Panel Name',
  title_corporate_panel_name: 'Corporate Panel Name',
  button_update_changes: 'Update Changes',
  title_time_user_requested_for_trip: 'Time User Requested for Trip',
  title_trip_start_time: 'Trip Start Time',
  title_trip_end_time: 'Trip End Time',
  title_invoice: 'Tax Invoice',
  title_provider_weekly_statement: 'Driver Weekly Earning',
  button_add_new_Admin: 'Add Admin',
  button_add_language: 'Add Language',
  title_lang_name: 'Name',
  button_add_new_promo: 'Add Promo',
  button_edit_promo_code: 'Edit Promo',
  title_cancel_date: 'Cancel Date',
  button_clear: 'Clear',
  title_active_providers: 'Active Drivers',
  title_inactive_providers: 'Inactive Drivers',
  title_car_model: 'Car Model',
  title_car_number: 'Car Number',
  title_rating: 'Rating',
  button_add_document: 'Add Document',
  title_number_of_uses: 'Number of Uses',
  title_expiry_date: 'Expiry Date',
  title_select_type: 'Select Type...',
  title_accessibility_peference: 'Accessibility Preference',
  title_absolute: 'Absolute',
  title_percentage: 'Percentage',
  title_ios_certificate_mode: 'Certificate Mode',
  title_sandbox: 'Sandbox',
  title_production: 'Production',
  title_total_users: 'Total Users',
  title_total_providers: 'Total Drivers',
  title_total_active_providers: 'Total Active Drivers',
  title_total_countries: 'Total Countries',
  title_bonus: 'Bonus',
  title_total_provider_have_cash: 'Driver Have Cash',
  title_total_trips: 'Total Trips',
  title_total_completed_trips: 'Total Completed Trips',
  title_total_cancelled_by_user: 'Cancelled by user',
  title_total_cancelled_by_provider: 'Cancelled by Driver',
  title_total_yet_to_be_paid: 'Yet to be Paid',
  title_total_refferal_payment: 'Referral',
  title_total_promotional_payment: 'Promotional',
  title_payment_from_countries: 'Payment from Countries',
  titel_request_detail: 'Request Detail',
  title_select_provider: 'Select Driver',
  title_floor: 'Floor',
  title_room_number: 'Room Number',
  title_user_miscellaneous_fee: 'User Miscellaneous Fee',
  title_user_tax: 'User Tax',
  title_provider_miscellaneous_fee: 'Driver Miscellaneous Fee',
  title_provider_tax: 'Driver Tax',
  title_user_login: 'User Login',
  title_provider_login: 'Driver Login',
  user_panel_name: 'Ohm User',
  provider_panel_name: 'Ohm Driver',
  title_old_password: 'Old Password',
  title_confirm_password: 'Confirm Password',
  menu_title_history: 'History',
  menu_title_upload_document: 'Upload Documents',
  title_add_new_card: 'Add New Card',
  title_otp_verification: 'OTP Verification',
  title_selected_card: 'Selected Card',
  title_other_card: 'Other Card',
  title_select_default: 'Select Default',
  title_add_card: 'Add Card',
  reset_password: 'Reset Password',
  title_referral_code: 'Referral Code',
  title_referral_credit: 'Referral Credit',
  title_total_provider_earning: 'Driver Earning',
  title_total_admin_earning: 'Admin Earning',
  title_total_admin_earning_in_currency: 'Admin Earning(In Currency)',
  button_add_wallet: 'Add Wallet',
  title_add_wallet: 'Add Wallet',
  title_amount_limit: 'Amount Limit',
  title_cancelled_request: 'Cancelled',
  title_accepted_request: 'Accepted',
  title_acception_ratio: 'Acception Ratio',
  title_completion_ratio: 'Completion Ratio',
  title_edit_document: 'Edit Document',
  title_delete_document: 'Delete Document',
  title_document_picture: 'Document Picture',
  title_registered_date: 'Registered Date',
  button_add_city: 'Add City',
  button_add_airport: 'Add Airport',
  button_add_destination_city: 'Add Destination City',
  button_add_zone: 'Add Zone',
  title_destination_city: 'Destination City',
  title_select_destination_city: 'Select Destination City...',
  title_selected_destination_city: 'Selected Destination City',
  title_bussiness_in_airport: 'Airport Business',
  title_bussiness_in_destination_city: 'Destination City Business',
  title_bussiness_in_zone: 'Zone Business',
  title_aiport_additional_charges: 'Airport Parking/Toll Charges',
  title_zone_kml_file: 'Zone KML File',
  title_country_business: 'Country Business',
  title_city_business: 'City Business',
  title_type_business: 'Type Business',
  button_ride_later: 'Ride Later',
  title_trip_information: 'Trip Information',
  title_trip_time_descriptiom: 'Trip Time Description',
  title_create_time: 'Create Time',
  title_provider_reach_time: 'Driver Reach Time',
  title_started_time: 'Started Time',
  title_ended_time: 'Ended Time',
  title_arrived_time: 'Arrived Time',
  title_min_fare: 'Min Fare',
  title_select_data_time: 'Please select date and time first',
  title_select_prpper_time: 'Please Select Proper Time',
  title_promo_amount: 'Promo Amount',
  title_total_amount_used: 'Total Amount Used',
  button_promo_used_info: 'Promo Used Info',
  title_logout: 'Logout',
  title_provider_vehicle: 'Driver Vehicle',
  title_not_approved: 'Not Approved',
  title_model: 'Car Model',
  title_color: 'Color',
  title_passing_year: 'Manufacturing Year',
  title_vehicle: 'Vehicle',
  title_ride_with: 'Ride with',
  title_drive_with: 'Drive with',
  title_partner_with: 'Partner with',
  title_dispatcher_with: 'Dispatcher With',
  button_signup_to_drive: 'SIGN UP TO DRIVE',
  button_signup_to_ride: 'SIGN UP TO RIDE',
  button_signup_to_partner: 'SIGN UP TO PARTNER',
  title_server_time: 'Server Time',
  title_city_time: 'Pick Up Time',
  title_promo_code: 'Promo Code',
  title_select_payment_method: 'select payment method',
  title_estimate: 'Estimate',
  title_enter_pickup_address: 'Enter Pickup address',
  title_enter_dest_address: 'Enter Destination address',
  button_apply_promo: 'Apply Promo',
  title_please_add_card_first: 'Please Add Card First',
  title_later: 'Later',
  title_creation_time: 'Requested At',
  title_road_api_google_key: 'Road API Google Key',
  title_android_places_autocomplete_key:
    'Android Places Auto Complete Google Key',
  title_ios_places_autocomplete_key: 'IOS Places Auto Complete Google Key',
  title_created_date: 'Created Date',
  title_completed_date: 'Complete Date',
  title_display_date_timezone: 'Display Date Timezone',
  button_add_vehicle: 'Add Vehicle',
  menu_title_vehicle: 'Manage Vehicle',
  button_edit_vehicle: 'Edit Vehicle Detail',
  title_url: 'Url',
  button_city_map: 'City Map',
  title_is_use_city_boundary: 'Use City Boundary',
  title_is_auto_transfer_in_country: 'Auto Transfer',
  title_auto_transfer_day: 'Auto Transfer Day',
  received: 'Received',
  online_mins: 'Online Minutes',
  title_remaining_payment: 'Remaining Payment',
  title_partner_earning: 'Partner Earning',
  button_assign_vehicle: 'Assign Vehicle',
  button_remove_vehicle: 'Remove Vehicle',
  title_remove: 'Remove',
  title_auto_transfer_time_zone: 'Auto Transfer Timezone',
  title_firebase_key: 'Firebase Key',
  title_firebase_apiKey: 'Firebase Api Key',
  title_firebase_authDomain: 'Firebase Auth Domain',
  title_firebase_databaseURL: 'Firebase Database Url',
  title_firebase_projectId: 'Firebase Project Id',
  title_firebase_storageBucket: 'Firebase Storage Bucket',
  title_firebase_messagingSenderId: 'Firebse Messaging Sender Id',
  title_from: 'From',
  title_to: 'To',
  select_zone1: 'Select Zone1',
  select_zone2: 'Select Zone2',
  zone_to_zone_price: 'Zone to Zone Price',
  zone_for_queue: 'Zone For Queue',
  airport_to_city_price: 'Airport to City Price',
  city_to_city_price: 'City to City Price',
  TRIP_TYPE_NORMAL_STRING: 'Normal',
  TRIP_TYPE_VISITOR_STRING: 'Visitor',
  PRICE_TYPE_NORMAL_STRING: 'Normal',
  PRICE_TYPE_POOL_STRING: 'Car Pool',
  sun: 'Sun',
  mon: 'Mon',
  tue: 'Tue',
  wed: 'Wed',
  thu: 'Thu',
  fri: 'Fri',
  sat: 'Sat',
  title_surge_time: 'Surge Time',
  add_time: 'Add Time',
  surge_start_time: 'Surge Start Time',
  surge_end_time: 'Surge End Time',
  surge_multiplier: 'Surge Multiplier',
  surge_time_error: 'End time must be greater than the start time',
  please_select_proper_time: 'Please Select Proper Time',
  surge_multiplier_is_required: 'Surge Multiplier is required',
  select_start_end_time: 'Please Select Start And End Time',
  title_detail: 'Detail',
  car_rental: 'Car Rental Package',
  car_rental_price: 'Car Rental Price',
  title_is_car_rental_business: 'Car Rental Business',
  add_package: 'Add Package',
  title_package_name: 'Package Name',
  title_twilio_call_masking: 'Twilio Call Masking',
  button_red_zone_area: 'Red Zone Area',
  rich_area_surge: 'Rich Area Surge',
  button_chat_history: 'Chat History',
  title_corporate: 'Corporate',
  corporate_panel_name: 'Corporate Panel',
  title_corporate_login: 'Corporate Login',
  button_new_request: 'New Request',
  button_accepted_request: 'Accepted',
  button_arrived_request: 'Arrived',
  button_started_request: 'Started',
  button_complete: 'Complete',
  default_selected: 'Default Selected',
  title_partner_vehicle: 'Partner Vehicle',
  title_yes: 'Yes',
  title_no: 'No',
  title_request_send_to_no_of_providers: 'Request Send To Number Of Driver',
  title_find_nearest_driver_type: 'Nearest Driver Type',
  single: 'Single',
  multiple: 'Multiple',
  title_terms_and_condition: 'Terms and Condition',
  title_privacy_policy: 'Privacy policy',
  title_user_terms_and_condition: 'User Terms and Condition',
  title_user_privacy_policy: 'User Privacy Policy',
  title_provider_terms_and_condition: 'Driver Terms and Condition',
  title_provider_privacy_policy: 'Driver Privacy Policy',
  title_provider_offline_min: 'Driver Offline min',
  title_domain: 'Domain',
  gmail: 'gmail',
  other: 'other',
  title_smtp_host: 'Smtp Host',
  title_smtp_port: 'Smtp Port',
  title_provider_referral_in_country: 'Driver Referral',
  title_default_referral_bonus_to_provider:
    'Referral Bonus Amount to Friend (Driver)',
  title_default_bonus_to_referral_provider:
    'Referral Bonus Amount to Self (Driver)',
  title_provider_referral_max_use: 'Referral Max Usage (Driver)',
  is_show_estimation_in_provider_app: 'Show Estimation in Driver App',
  is_show_estimation_in_user_app: 'Show Estimation in User App',
  title_male: 'Male',
  title_female: 'Female',
  title_postal_code: 'Postal Code',
  title_file_1: 'Upload Photo ID - Front',
  title_file_2: 'Upload Photo ID - Back',
  title_file_3: 'Upload Additional Document',
  'config_json.message_welcome_login': 'config_json.message_welcome_login',
  app_name: 'app_name',
  Admin_subadmin: 'Admin_subadmin',
  Approve: 'Approve',
  Decline: 'Decline',
  Active: 'Active',
  Inactive: 'Inactive',
  title_add_corporate: 'Add Corporate',
  title_edit_corporate: 'Edit Corporate',
  title_is_action: 'Action',
  title_user_panel: 'User Panel',
  tooltip_twiml_url: 'twiml url',
  TRIP_TYPE_HOTEL: 'TRIP_TYPE_HOTEL',
  edit_profile: 'EDIT PROFILE',
  change_password: 'CHANGE PASSWORD',
  add_now: 'Add Now',
  please_enter_promo_code: 'Please Enter Promo Code',
  old_password: 'Old Password',
  new_password: 'New Password',
  re_enter_new_password: 'Re-enter New Password',
  balance: 'Balance',
  page_number: 'Page Number',
  full_name: 'full name',
  username: 'Username',
  android_user: 'Android User',
  ios_user: 'Ios User',
  android_provider: 'Android Driver',
  ios_provider: 'Ios Driver',
  bank: 'Bank',
  manual_cash: 'Manual (Cash)',
  is_zone: 'Is Zone',
  statistics: 'STATISTICS',
  PAYMENT_TRANSACTIONS: 'PAYMENT TRANSACTIONS',
  service_price: 'Service Price',
  surge_price: 'Surge Price',
  miscellaneous_fees: 'Miscellaneous Fees',
  toll_amount: 'Toll Amount',
  tip_amount: 'Tip Amount',
  deduct_wallet_amount: 'Deduct Wallet Amount',
  added_wallet_amount: 'Added Wallet Amount',
  total_earnings: 'TOTAL EARNING',
  paid_in_wallet: 'PAID IN WALLET',
  transferred_amount: 'Transferred Amount',
  trip_no: 'Trip No.',
  profit: 'Profit',
  earn: 'Earn',
  city_list: 'City List',
  admin_curency_code: 'Admin Curency Code',
  admin_curency: 'Admin Curency',
  this_is_admin_mobile_number: 'This is admin mobile number',
  this_email_address_will_get_email_notification_about_request:
    'This email address will get E-mail notification about request',
  this_email_address_for_contact_us: 'This email address for contact Us',
  maximum_time_for_provider_to_respond_for_a_request:
    'Maximum time for driver to respond for a request',
  defalt_search_radius_to_look_for_providers:
    'Defalt search radius to look for drivers',
  minutes_before_scheduled_request:
    'Minutes before scheduled request time when system should start searching driver for that request',
  number_of_times_system_should_retry:
    'Number of times system should retry if no drivers are found in scheduled requests.',
  send_sms_notification: 'Send SMS Notification.',
  send_email_notification: 'Send E-mail Notification.',
  provider_path: 'Driver Path.',
  user_path: 'User Path.',
  referral_bonus_card_payment: 'Referral bonus can be cut while card payment.',
  referral_bonus_cash_payment: 'Referral bonus can be cut while cash payment.',
  send_email_verification_code: 'Send Email Verification Code.',
  send_sms_verification_code_user:
    'Send SMS Verification Code For User Mobile Number Verification.',
  send_sms_verification_code_provider:
    'Send SMS Verification Code For Driver Mobile Number Verification.',
  tip_for_trip: 'Tip On/Off for Trip.',
  toll_for_trip: 'Toll On/Off for Trip.',
  android_user_app_force_update: 'Android User App Force Update.',
  android_provider_app_force_update: 'Android Driver App Force Update.',
  ios_user_app_force_update: 'IOS User App Force Update.',
  ios_provider_app_force_update: 'IOS Driver App Force Update.',
  provider_initiate_trip: 'Driver Initiate Trip',
  twilio_call_masking: 'Twilio Call Masking',
  show_estimation_in_provider_app: 'Show Estimation in Driver App',
  show_estimation_in_user_app: 'Show Estimation in User App',
  please_upload_image_in_png_format: 'Please Upload image in .png format',
  success_message_dispatcher_add: 'Dispatcher Added Successfully',
  success_message_dispatcher_update: 'Dispatcher Updated Successfully',
  success_message_provider_update: 'Driver Updated Successfully',
  success_message_user_update: 'User Updated Successfully',
  success_message_hotel_add: 'Hotel Added Successfully',
  success_message_hotel_update: 'Hotel Updated Successfully',
  success_message_send_link: 'Send link to email',
  success_message_password_update: 'Password Updated Successfully',
  success_message_add_admin: 'Admin Added Successfully',
  success_message_add_language: 'Admin Language Successfully',
  success_message_update: 'Updated Successfully',
  success_message_delete: 'Delete successfully',
  success_message_login: 'Login Successful',
  success_message_registration: 'Registration Successful',
  success_message_bank_detail_add: 'Bank Detail Added Successfully',
  success_message_bank_detail_update: 'Bank Detail Updated Successfully',
  success_message_profile_update: 'Profile updated Successfully',
  success_message_trip_cancelled: 'Trip Cancelled Successfully',
  success_message_schedule_trip_create_successfully:
    'Request Created Successfully',
  success_message_add_card: 'Add Card Successfully',
  success_message_partner_approved: 'Partner Approved Successfully',
  success_message_partner_declined: 'Partner Declined Successfully',
  success_message_provider_approved: 'Driver Approved Successfully',
  success_message_provider_declined: 'Driver Declined Successfully',
  success_message_user_approved: 'User Approved Successfully',
  success_message_user_declined: 'User Declined Successfully',
  success_message_referralcode_apply: 'Referral Code Applied Successfully',
  profile_image_aspect_ratio: "'1:1'",
  success_message_add_limit: 'Add Limit Successfully',
  error_session_expired: 'Session Expired',
  error_message_email_not_registered: 'Email Not Registered',
  error_message_phone_not_registered: 'Phone Number Is Not Registered',
  error_message_token_expired:
    'Your link has expired please try resetting your password again',
  error_message_email_already_used: 'Email already registered',
  error_message_mobile_no_already_used: 'Mobile No already registered',
  error_message_password_wrong: 'Incorrect Password',
  error_message_admin_not_approved: 'You are not approved by Admin',
  error_message_current_password_wrong: 'Incorrect Current Password',
  error_message_referralcode_invalid: 'Invalid Referral Code ',
  error_message_document_not_uploaded:
    'Driver has not uploaded his documents yet',
  error_message_type_duplicate: 'Duplicated Type Name Found',
  error_message_email_or_username_not_registered:
    'Email or Username is not registered',
  error_message_promo_code_already_added_for_all_city:
    'Promo Code already added for All City',
  error_message_promo_code_already_added_for_same_city:
    'You cant add promo for same city',
  success_message_for_password_change: 'Check your mail for password set',
  success_message_service_type_update: 'Type detail Updated Successfully',
  success_message_service_type_add: 'Type Add Successfully',
  success_message_country_update: 'Country detail Updated Successfully',
  success_message_country_add: 'Country Add Successfully',
  success_message_city_update: 'City detail Updated Successfully',
  success_message_city_add: 'City Add Successfully',
  success_message_city_service_update:
    'City Service detail Updated Successfully',
  success_message_city_service_add: 'City Service Add Successfully',
  success_message_paid_pending: 'Successfully Paid',
  success_message_refund: 'Trip Amount Refund Successfully',
  error_message_refund: 'Trip Amount Refund Failed',
  error_message_for_profile_image_aspect_ratio:
    'Select image with appropriate aspect ratio',
  error_email_otp_not_match: 'Email Otp Not Match',
  error_sms_otp_not_match: 'Sms Otp Not Match',
  error_type_not_available: 'Type not Available',
  error_pickup_address: 'Enter Pickup Address',
  error_enter_destination_address: 'Enter Destination Address',
  error_trip_already_running: 'Trip Already Running',
  error_payment_is_pending: 'Payment Is Pending',
  error_not_supported_multiple_stop:
    'Multiple Stop Only Supports Requested Trips',
  error_provider_not_found: 'Driver Not Found',
  error_please_enter_promo_code: 'Please Enter Promo Code',
  error_enter_valid_promocode: 'Please Enter Valid Promo Code',
  error_promocode_already_used: 'Promo Code Already Used',
  error_promocode_expired: 'Promo Code Expired',
  error_add_card_first: 'Please Add Card First',
  error_message_provider_in_trip: 'Driver In Trip',
  success_promo_apply: 'Promo Code Apply Successfully',
  success_message_add_wallet: 'Add Wallet Succesfully',
  errpr_message_add_wallet_failed: 'Add Wallet Failed',
  error_message_promo_code_already_added_for_same_country:
    'Promo Already Added for this country',
  error_zone_already_added: 'Zone Already Added',
  error_trip_running: 'Trip Running',
  success_update_vehicle_detail: 'Update Vehicle Successfully',
  success_add_vehicle_detail: 'Add Vehicle Successfully',
  success_update_document: 'Document Upload Successfully',
  success_message_request_send_successfully:
    'Request Send to user successfully',
  success_message_user_removed_successfully: 'User Removed Successfully',
  error_please_add_card_first: 'Please Add Card First',
  error_create_trip_failed: 'Create Trip Failed',
  success_create_trip: 'Trip Created Successfully',
  error_promocode_not_for_your_area: 'Promo code not for your area',
  error_promocode_not_apply_on_your_payment_mode:
    'Promo code not apply on your payment mode',
  tooltip_twillio_account_sid:
    'Twilio is a SMS Gateway.If you want system to send SMS then you must sign up with twillio and get your SID.',
  tooltip_twilio_auth_token:
    'Twilio Auth Token is used to authenticate your Twillio App.',
  tooltip_twilio_number:
    'Twilio provides a number from which your SMS will be sent.',
  tooltip_default_payment_gateway:
    'Stripe is the default payment gateway. Stripe process payment from customer and deliver it to admin.',
  tooltip_stripe_secret_key:
    'Secret and publishable keys are used to identify your Stripe account. You can grab the test and live API keys for your account under Your Account >> API Keys. The publishable key is used to generate credit card tokens and should be included with the HTML form.',
  tooltip_stripe_publishable_key:
    'Secret and publishable keys are used to identify your Stripe account. You can grab the test and live API keys for your account under Your Account >> API Keys. The publishable key is used to generate credit card tokens and should be included with the HTML form.',
  tooltip_email_display_name:
    'From name in the email sent by server. Example Ohm Server',
  tooltip_email_domain_email_address:
    'From email address of your domain which will be used to send email. Example: noreply@elluminatiinc.com',
  tooltip_android_user_app_gcm_key:
    'GCM Key is used for push notification in User App.',
  tooltip_android_provider_app_gcm_key:
    'GCM Key is used for push notification in Driver App.',
  tooltip_user_google_places_api_key:
    'Google places API is required to draw path in user App get nearby places in Fare Estimate and auto complete suggestion for source and destination address.',
  tooltip_provider_google_places_api_key:
    'Google places API is required to draw path in driver app.',
  tooltip_web_google_places_api_key:
    'Google places API is required in dispatcher panel for auto complete suggestions of places.It is also used in Map view of Admin Panel for Auto complete results of places.',
  tooltip_hotline_app_id:
    'ID for Customer Support system Hotline.io goes here.',
  tooltip_hotline_app_key:
    'Key for Customer Support system Hotline.io goes here.',
  tooltip_ios_driver_app_url:
    'iOS Driver App URL goes here. It is used in the landing page.',
  tooltip_ios_client_app_url:
    'iOS Client App URL goes here. It is used in the landing page.',
  tooltip_android_driver_app_url:
    'Android Driver App URL goes here. It is used in the landing page.',
  tooltip_android_client_app_url:
    'Android Client App URL goes here. It is used in the landing page.',
  tooltip_admin_phone_number:
    'This phone number will be used for contacting admin.',
  tooltip_admin_email_address: 'This email will be used for contacting admin.',
  tooltip_contact_email:
    'This email will be used as contact email in the Apps.',
  tooltip_provider_timeout_in_seconds:
    'Number of seconds system should wait for driver to respond for the incoming request.',
  tooltip_default_search_radius: 'Default search radius to look for drivers',
  tooltip_scheduled_request_pre_start_minutes:
    'System should search for nearest driver before defined time.',
  tooltip_number_of_loop_for_scheduled_requests:
    'Number of times system should retry if no drivers are found in scheduled requests.',
  tooltip_ios_user_passphrase: 'User App Certificate Passphrase.',
  tooltip_ios_provider_passphrase: 'Driver App Certificate Passphrase.',
  tooltip_currency_name:
    'You can write the name of currency for this country. Example Rupee for INR Dollar for USD etc.',
  tooltip_referral_bonus_amount_to_friend:
    "Please enter the amount of Referral bonus credit User's friend should get. Credit Currency will be default country currency.",
  tooltip_referral_bonus_amount_to_self:
    'Please enter the amount of Referral bonus credit User should get if his Referral code is used. Credit Currency will be default country currency.',
  tooltip_user_referral_max_use:
    "This number indicates maximum usage of user's referral code. If entered 2 then user's code will be used only 2 times by different friends.",
  tooltip_city_zip_code: 'Zip Code or Postal Code of the city.',
  tooltip_title_provider_min_wallet_amount_set_for_received_cash_request:
    'Driver Minimum Wallet Amount For Cash.',
  tooltip_phone_number_length: 'Phone Number Length.',
  tooltip_city_code: 'Enter the code for the city. Eg. RAJ for Rajkot city.',
  tooltip_city_longitude: "Longitude coordinate of city's centre.",
  tooltip_city_latitude: "Latitude coordinate of the city's centre.",
  tooltip_city_radius:
    "This is the integer value of service area for this city. Eg. 20 Km or miles depending on country's distance unit.",
  tooltip_max_space:
    'Maximum number of people this service type can accommodate.',
  tooltip_surge_time_end:
    'Select the time when you want to end the surge pricing.',
  tooltip_surge_multiplier:
    'Enter the multiplier for surge pricing. Eg 1.5 which will raise the price by 1.5 times the original price.',
  tooltip_cancellation_fee:
    'This is the fees charged on cancellation of the trip / Rental Package.',
  tooltip_price_for_waiting_time: 'Enter the flat charge for waiting time.',
  tooltip_base_price:
    'Base price for this service type. Eg. $5 is the base price for SUV.',
  tooltip_min_fare: 'Minimum fare.',
  tooltip_surge_time_start:
    'Select the time when you want to start the surge pricing.',
  tooltip_is_surge_hours: 'You can make surge pricing On or Off from here.',
  tooltip_tax: 'Percentage of tax on the total invoice.',
  tooltip_waiting_time_start_after_minute:
    'Enter the Integer value for free waiting time. Eg. if entered 5 then waiting time charges will be calculated after 5 minutes.',
  tooltip_price_per_unit_distance:
    'Price per km or mile for this service type.',
  tooltip_distance_for_base_price:
    'Select the value for free distance covered in base price. Eg. if selected 2 then distance price will not be charged till 2 km or miles.',
  tooltip_provider_profit:
    'Percentage of profit driver or driver should get for this service type.',
  tooltip_admin_panel_name: 'Admin panel name.',
  tooltip_dispatcher_panel_name: 'Dispatcher panel name.',
  tooltip_partner_panel_name: 'Partner panel name.',
  tooltip_android_user_app_version_code: 'Android User App Version.',
  tooltip_android_provider_app_version_code: 'Android Driver App Version.',
  tooltip_ios_user_app_version_code: 'Ios User App Version.',
  tooltip_ios_provider_app_version_code: 'Ios Driver App Version.',
  tooltip_user_miscellaneous_fee:
    'Percentage of user miscellaneous fee on the total invoice.',
  tooltip_user_tax: 'Percentage of user tax on the total invoice.',
  tooltip_provider_miscellaneous_fee:
    'Percentage of povider miscellaneous fee on the total invoice.',
  tooltip_provider_tax: 'Percentage of user tax on the total invoice.',
  tooltip_road_api_google_key: 'FOR ROAD API KEY',
  tooltip_provider_offline_min: 'Driver Offline after min',
  pickup: 'pickup',
  destination: 'destination',
  nearest: 'Nearest',
  manual: 'Manual',
  cash: 'Cash',
  others: 'UPI/Other',
  select_time: 'select_time',
  go_to: 'Go to',
  provider_location: 'Driver Location',
  pickup_location: 'Pickup Location',
  stops_location: 'Stops Location',
  destination_location: 'Destination Location',
  refund: 'Refund',
  messages: 'Messages',
  change_photo: 'Change Photo',
  we_used_fare_price: 'We have used fare price',
  is_default_selected: 'is default selected',
  title_select_type_priority: 'title select type priority',
  upload_type_image: 'upload type image',
  upload_map_pin_image: 'upload map pin image',
  change_type_image: 'change type image',
  change_map_pin_image: 'change map pin image',
  image_with_appropriate_aspect_ratio: 'image with appropriate aspect ratio',
  tooltip_email_smtp_host: 'email smtp host',
  tooltip_smtp_port: 'smtp port',
  tooltip_hotel_panel_name: 'Hotel panel name.',
  tooltip_corporate_panel_name: 'Corporate panel name.',
  tooltip_request_send_to_no_of_providers: 'request send to no of drivers',
  all_type: 'All Type',
  baby_seat: 'Baby Seat',
  hotspot: 'Hot Spot',
  handicap: 'Handicap',
  Normal: 'Normal',
  Visitor: 'Visitor',
  title_change_document_picture: 'Change Document Picture',
  tooltip_price_for_total_unit_time: 'price for total unit time',
  tooltip_is_business: 'is business',
  tooltip_user_miscellaneous_tax: 'user miscellaneous tax',
  tooltip_provider_miscellaneous_tax: 'driver miscellaneous tax',
  title_card_number: 'Card Number',
  title_completed_request: 'Completed',
  title_no_expiry_date: 'No Expiry Date',
  title_no_unique_code: 'No Unique Code',
  title_select_date: 'Select Date',
  title_select_time: 'Select Time',
  title_provider_location: 'Driver Location',
  title_pickup_location: 'Pickup Location',
  title_destination_location: 'Destination Location',
  title_invoice_fare: 'Fare',
  title_no_provider_found: 'No Driver Found',
  title_your_business_is_only: 'Your Business Is Only in ',
  title_change_photo: 'Change Photo',
  title_upload_photo: 'Upload Photo',
  title_nothing_selected: 'Nothing Selected',
  change_id_proof: 'Change Id Proof',
  title_specific_number: 'Specific number of completed trips',
  title_minimum_number: 'Minimum number of completed trips',
  title_completed_trips: 'Completed trips',
  title_number_of_trips: 'Number of trips',
  title_p8_push_file: 'P8 Push file',
  title_user_bundle_id: 'User Bundle Id',
  title_provider_bundle_id: 'Driver Bundle Id',
  title_team_id: 'Team Id',
  title_key_id: 'Key Id',
  title_edit_dispatcher: 'Edit Dispatcher',
  title_banking_detail: 'Banking Detail',
  title_edit_hotel: 'Edit Hotel',
  title_add_hotel: 'Add Hotel',
  title_partner_details: 'Partner Detail',
  title_edit_type: 'Edit Type',
  title_user_review: 'User Review',
  title_provider_review: 'Driver Review',
  title_pin_title: 'PIN',
  title_otp_title: 'OTP',
  title_phone_title: 'Phone',
  title_address_title: 'Address',
  title_pin: 'PIN',
  title_otp: 'OTP',
  title_paystack_secret_key: 'Paystack Secret Key',
  title_paystack_publishable_key: 'Paystack Public Key',
  title_payu_key: 'Payu Key',
  title_payu_salt: 'Payu Salt',
  title_edit_vehicle: 'Edit Vehicle Detail',
  title_add_vehicle: 'Add Vehicle Detail',
  menu_title_trip_map: 'Trip Map',
  menu_title_trip_invoice: 'Trip Invoice',
  menu_title_user_detail: 'User Detail',
  menu_title_user_history: 'User History',
  menu_title_provider_history: 'Driver History',
  menu_title_edit_promo: 'Edit Promo Code',
  menu_title_partner_add_vehicle: 'Partner Add Vehicle Details',
  menu_title_partner_edit_vehicle: 'Partner Update Vehicle Details',
  label_no_data_found: 'No data Found',
  month1: 'Jan',
  month2: 'Feb',
  month3: 'Mar',
  month4: 'Apr',
  month5: 'May',
  month6: 'Jun',
  month7: 'Jul',
  month8: 'Aug',
  month9: 'Sep',
  month10: 'Oct',
  month11: 'Nov',
  month12: 'Dec',
  city_validation_field_required: 'Enter Valid City.',
  validation_field_required: 'This field is required.',
  title_pick_up_at: 'Pick Up at',
  title_start_for_pickup: 'Start for Pickup',
  error_message_document_already_added_for_country:
    'Document already added for this Country',
  button_unfreeze: 'Unfreeze',
  success_message_provider_unfreeze: 'Trip Removed From Driver Successfully',
  validation_enter_valid_email: 'Enter Valid Email',
  validation_enter_valid_address: 'Enter Valid Address',
  validation_enter_valid_phone: 'Enter Valid Phone No',
  validation_min_length: 'Please enter at least {0} characters.',
  validation_max_length: 'Please enter no more than {0} characters.',
  validation_range_min_length:
    'Please enter a value less than or equal to {0}.',
  validation_range_max_length:
    'Please enter a value greater than or equal to {0}.',
  validation_reenter_password: 'Please enter the same value again.',
  validation_file_select: 'Please select file with valid extension.',
  add_admin: 'Add Admin',
  add_city_form: 'Add City Form',
  add_city_type_form: 'Add City Type Form',
  add_country_form: 'Add Country Form',
  add_dispatcher: 'Add Dispatcher',
  add_document_form: 'Add Document Form',
  add_hotel: 'Add Hotel',
  add_promo_form: 'Add Promo Form',
  add_provider_vehicle: 'Add Driver Vehicle',
  add_service_form: 'Add Service Form',
  admin_dispatcher_bank_detail: 'Admin Dispatcher Bank Detail',
  admin_partner_bank_detail: 'Admin Partner Bank Detail',
  admin_partner_weekly_earning_statement:
    'Admin Partner Weekly Earning Statement',
  chat_history: 'Chat History',
  corporate_trip_map: 'Corporate Trip Map',
  customer_detail_edit: 'Customer Detail Edit',
  dispatcher_trip_map: 'Dispatcher Trip Map',
  edit_admin: 'Edit Admin',
  edit_city_form: 'Edit City Form',
  edit_city_type_form: 'Edit City Type Form',
  edit_corporate: 'Edit Corporate',
  edit_country_form: 'Edit Country Form',
  edit_dispatcher: 'Edit Dispatcher',
  edit_document_form: 'Edit Document Form',
  edit_hotel: 'Edit Hotel',
  edit_partner_vehicle_detail: 'Edit Partner Vehicle Detail',
  edit_service_form: 'Edit Service Form',
  edit_vehicle_detail: 'Edit Vehicle Detail',
  history_pr: 'Driver History',
  history_u: 'User History',
  hotel_trip_map: 'Hotel Trip Map',
  partner_add_provider: 'Partner Add Driver',
  partner_add_vehicle: 'Partner Add Vehicle',
  partner_detail: 'Partner Detail',
  partner_edit_vehicle_detail: 'Partner Edit Vehicle Detail',
  partner_proivder_documents: 'Partner Driver Documents',
  partner_provider_bank_detail: 'Partner Driver Bank Detail',
  partner_provider_documents_edit: 'Partner Driver Documents Edit',
  partner_provider_edit: 'Partner Driver Edit',
  partner_provider_history: 'Partner Driver History',
  partner_provider_list: 'Partner Driver List',
  partner_trip_map: 'Partner Trip Map',
  partner_vehicle_list: 'Partner Vehicle List',
  profile_detail_edit: 'Profile Detail Edit',
  proivder_documents: 'Driver Documents',
  promo_used_info: 'Promo Used Info',
  promocodeedit: 'Edit Promo Code',
  provider_bank_detail: 'Driver Bank Detail',
  provider_documents_edit: 'Driver Documents Edit',
  provider_referral_history: 'Driver Referral History',
  provider_vehicle_list: 'Driver Vehicle List',
  referral_history: 'Referral History',
  review_detail: 'Review Detail',
  statement_provider_daily_earning: 'Statement Driver Daily Earning',
  statement_provider_earning: 'Statement Driver Earning',
  statement_provider_weekly_earning: 'Statement Driver Weekly Earning',
  trip_invoice: 'Trip Invoice',
  trip_map: 'Trip Map',
  user_detail: 'User Detail',
  user_documents: 'User Documents',
  vehicle_document_list: 'Vehicle Document List',
  vehicle_document_list_for_partner: 'Vehicle Document List For Partner',
  vehicle_document_list_partner: 'Vehicle Document List Partner',
  vehicle_documents_edit_for_partner: 'Vehicle Documents Edit For Partner',
  title_refund_trip: 'Refund Trip Amount',
  select_payment_type: 'Select Payment Type',
  title_home_address: 'Home Address',
  title_work_address: 'Work Address',
  success_message_address_saved: 'Address Saved SuccessFully',
  error_message_address_saved: 'Address Saved Failed',
  success_message_address_removed: 'Address Removed SuccessFully',
  error_message_address_removed: 'Address Removed Failed',
  error_message_business_not_in_your_country:
    'Business Not Running In Your Country',
  error_message_business_not_in_your_city: 'Business Not Running In Your City',
  error_message_business_not_in_your_area: 'Business Not Running In Your Area',
  title_car_rental: 'Car Rental',
  title_invoice_total_distance_extra: 'Extra Distance Charge',
  title_invoice_total_time_extra: 'Extra Time Charge',
  button_send: 'Send',
  label_enter_your_message: 'Enter your message...',
  button_chat: 'Chat',
  menu_title_guest_token_setting: 'Guest Token',
  title_token_name: 'Token Name',
  title_token_value: 'Token Value',
  button_add_new_guest_token: 'Add New Guest Token',
  button_edit_guest_token: 'Edit Guest Token',
  user_social_login: 'User Social Login',
  provider_social_login: 'Driver Social Login',
  country_not_found: 'Country Not Found',
  trip_not_found: 'Trip Not Found',
  minimum_phone_number_length: 'Minimum Phone No Length',
  tooltip_minimum_phone_number_length: 'Minimum Phone No Length',
  maximum_phone_number_length: 'Maximum Phone No Length',
  tooltip_maximum_phone_number_length: 'Maximum Phone No Length',
  title_surge_price: 'Surge Fees',
  title_promo_bonus: 'Promo Bonus',
  title_airport_add: 'Airport Parking/Toll Charges',
  title_service_price: 'Service Fees',
  title_total_service_price: 'Total Service Price',
  title_min_fare_applied: '( Minimum Fare Applied )',
  title_fixed_price_applied: '( Fixed Price Applied )',
  title_airport_price_applied: '( Airport Price Applied )',
  title_zone_to_zone_price_applied: '( Zone to Zone Price Applied )',
  title_city_to_city_price_applied: '( City to City Price Applied )',
  title_otp_verification_to_start: 'OTP Verification To Start With The Ride',
  title_otp_verification_to_start_desc:
    'The driver will ask for the OTP confirmation code from the user to begin the trip.',
  title_trip_feature_settings: 'Trip Feature Settings',
  title_accept_new_request_on_destination:
    'Can we allow driver to accept new request when near destination of trip ?',
  title_accept_new_request_on_destination_desc:
    'So in this feature, allow driver to accept trip when driver current trip is running and driver near to user destination. If driver have normal trip then and only then he will receive request.',
  title_accept_new_request_on_destination_radius:
    'How much radius set from destination location to received trip ? (in meter)',
  title_accept_new_request_on_destination_radius_desc:
    'As deine radius, this will help to find driver when he in trip',
  title_allow_driver_go_home: 'Do allow driver to enable go to home feature ?',
  title_allow_driver_go_home_desc1:
    'If driver want to go home then, he will only receive trip that destination under circle from driver home location',
  title_allow_driver_go_home_desc2:
    'If driver click on offline then Going to home turn OFF automatically',
  title_allow_driver_change_address:
    'Are we allow driver can change address after set ?',
  title_allow_driver_change_address_desc:
    'If this is disabled then driver will not change address after set, if he want to change address then have to contact admin',
  title_allow_driver_go_home_radius:
    'How much radius set from driver home destination location to received trip ? (in meter)',
  title_allow_driver_go_home_radius_desc:
    'As define radius, this will help to find provider when he is in trip',
  title_allow_multiple_stop: 'Can user add multiple stop in trip ?',
  title_allow_multiple_stop_desc:
    'If user booked trip then he cann add X times stops between pickup and destination',
  title_allow_waiting_time_charges:
    'Waiting time charges calculate on every stop ? (or one time)',
  title_allow_waiting_time_charges_desc1:
    'Charges you can set on Type and Association page.You can set waiting time charge and free min.',
  title_allow_waiting_time_charges_desc2:
    'If this is enable then every stop free min will apply and after charges calculate, else we will maku sum of waiting time and apply free min one time',
  title_allow_how_many_stop:
    'How many stop user can enter in trip ? (destination not included in this)',
  title_free_waiting_time_multiple_locatin:
    'Free Waiting Time ( For Multiple Location )',
  title_free_waiting_time_price_multiple_locatin:
    'Price For Waiting Time ( For Multiple Location )',
  title_add_stop: '+ Add Stop',
  title_stops: 'Stops',
  title_stop: 'Stop',
  validation_stop_limit: 'You Have Reached To Max Limit.',
  title_allow_ride_share: 'Can user can do ride share ?',
  title_allow_ride_share_desc: 'Can user can do ride share ?',
  title_ride_share_pickup_radius:
    'Set radius for pickup new user with driver current location (in km)',
  title_ride_share_destination_radius:
    'Set radius for destination area (in km)',
  can_not_refund_more_than_trip_amount: 'Can not refund more than total amount',
};
